# Generated by Django 3.2.18 on 2023-04-28 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230428_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
