# Generated by Django 3.2.18 on 2023-04-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.DateField(default='2023-05-07'),
        ),
        migrations.AddField(
            model_name='post',
            name='start_date',
            field=models.DateField(default='2023-05-01'),
        ),
    ]
