# Generated by Django 3.2.18 on 2023-04-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='region',
        ),
    ]
