# Generated by Django 3.2.18 on 2023-04-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlecomment_like_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_content', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tagging',
            field=models.ManyToManyField(related_name='tagged', to='articles.Tag'),
        ),
    ]
