# Generated by Django 3.2.18 on 2023-04-30 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_articlecomment_like_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_content', models.TextField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='bookmark_user',
            field=models.ManyToManyField(related_name='bookmark_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='tagging',
            field=models.ManyToManyField(blank=True, related_name='tagged', to='articles.Tag'),
        ),
    ]
