# Generated by Django 3.2.18 on 2023-04-30 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_auto_20230430_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.ManyToManyField(related_name='view_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
