# Generated by Django 3.2.18 on 2023-04-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20230428_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tagging',
            field=models.ManyToManyField(blank=True, related_name='tagged', to='articles.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_content',
            field=models.TextField(blank=True, max_length=20, unique=True),
        ),
    ]
