# Generated by Django 3.2.18 on 2023-04-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20230428_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_content',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
