# Generated by Django 3.2.18 on 2023-05-01 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20230501_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='emote_user',
            new_name='emotions',
        ),
    ]
