# Generated by Django 3.2.18 on 2023-05-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_emote_user_articlecomment_emotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecommentemote',
            name='emotion',
            field=models.CharField(choices=[('like', '좋아요'), ('dislike', '싫어요')], max_length=10),
        ),
    ]
