# Generated by Django 3.2.18 on 2023-05-01 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0007_alter_articlecommentemote_emotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='emotions',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='dislike_user',
            field=models.ManyToManyField(related_name='dislike_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ArticleCommentEmote',
        ),
    ]
