# Generated by Django 3.2.18 on 2023-04-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230427_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follower',
            new_name='followers',
        ),
    ]
