
# Generated by Django 3.2.18 on 2023-05-02 08:41


import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_follower_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=accounts.models.User.profile),
        ),
    ]

